version: '3.4'

x-enviroment: &commonEnv
    - 'GOOGLE_APPLICATION_CREDENTIALS=/code/GCP_KEY.json'
    - 'HOST=na1.api.riotgames.com'
    - 'GCLOUD_PROJECT=ordinal-cacao-291815'
    - 'REGION=NA'
    - 'PYTHONUNBUFFERED=0'

x-baseContainer: &baseContainer
  build: .
  environment: *commonEnv

services:
  master:
    <<: *baseContainer
    env_file:
      - env/.env.master
  diamond:
    <<: *baseContainer
    env_file:
      - env/.env.diamond
  platnium:
    << : *baseContainer
    env_file:
      - env/.env.platinum
  gold:
    <<: *baseContainer
    env_file:
      - env/.env.gold
  silver:
    <<: *baseContainer
    env_file:
      - env/.env.silver
  bronze:
    <<: *baseContainer
    env_file:
      - env/.env.bronze
  iron:
    <<: *baseContainer
    env_file:
      - env/.env.iron