version: '3.4'

services:
  br1:
    build: .
    env_file:
      - env/.env.br1
  eun1:
    build: .
    env_file:
      - env/.env.eun1
  euw1:
    build: .
    env_file:
      - env/.env.euw1
  jp1:
    build: .
    env_file:
      - env/.env.jp1
  kr:
    build: .
    env_file:
      - env/.env.kr
  la1:
    build: .
    env_file:
      - env/.env.la1
  la2:
    build: .
    env_file:
      - env/.env.la2
  na1:
    build: .
    env_file:
      - env/.env.na1
  oc1:
    build: .
    env_file:
      - env/.env.oc1
  tr1:
    build: .
    env_file:
      - env/.env.tr1
  ru:
    build: .
    env_file:
      - env/.env.ru