name: Deploy function to GCP

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_FUNCTION_CI }}
        export_default_credentials: true
    - run: gcloud functions deploy resize_and_clean --entry-point resize_and_clean --runtime python38 --trigger-resource dodge-bot --trigger-event google.storage.object.finalize --source=./data-mining/data-process-fnc/
# todo remove testing once function is stable
    - run: gcloud functions deploy resize_and_clean_testing --entry-point resize_and_clean --runtime python38 --trigger-resource dodge-bot-testing --trigger-event google.storage.object.finalize --source=./data-mining/data-process-fnc/
