name: Deploy function to GCP

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_FUNCTION_CI }}
        export_default_credentials: true
    - run: gcloud functions deploy hello_gcp --entry-point hello_gcp --runtime python38 --trigger-http --allow-unauthenticated --source=./data-mining/match-data/
