name: Deploy function to GCP

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: deploy
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: hello-gh
          runtime: python38
          credentials: ${{ secrets.GCP_FUNCTION_CI }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          source_dir: ./data-mining/match-data/hello_gcp.py
