name: Deploy Frontend to Firebase

on:
  push:
    branches:
      - master
    paths:
     - 'frontend/**'

env:
  REACT_APP_ML_URL: ${{ secrets.REACT_APP_ML_URL }}
  REACT_APP_COLLECTION_URL: ${{ secrets.REACT_APP_COLLECTION_URL }}
  REACT_APP_apiKey: ${{ secrets.REACT_APP_APIKEY }}
  REACT_APP_authDomain: ${{ secrets.REACT_APP_AUTHDOMAIN }}
  REACT_APP_databaseURL: ${{ secrets.REACT_APP_DATABASEURL }}
  REACT_APP_projectId: ${{ secrets.REACT_APP_PROJECTID }}
  REACT_APP_storageBucket: ${{ secrets.REACT_APP_STORAGEBUCKET }}
  REACT_APP_messagingSenderId: ${{ secrets.REACT_APP_MESSAGINGSENDERID }}
  REACT_APP_appId: ${{ secrets.REACT_APP_APPID }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
        working-directory: frontend
      - name: Build Project
        run: npm run build
        working-directory: frontend
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: build
          path: build
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: build
          path: ./frontend/build
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_PATH: ./frontend
