name: Docker Image - Riot Scraper Raw Data

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GH_CONTAINER_REGISTRY }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./data-mining/raw-data/
        file: ./data-mining/raw-data/Dockerfile 
        tags: ding-ma/riot-raw-data-scrapper:latest        
        platforms: linux/amd64
        push: true
