name: Docker Image - Riot Scraper Raw Data

on:
  push:
    branches:
      - master
    paths:
        - 'data-mining/raw-data/**'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_CONTAINER_REGISTRY }}
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8  
      - name: Install pip
        run: |
          pip install --upgrade pip
          sudo -H pip install -U pipenv
          pipenv install
          pipenv lock -r > raw-data/requirements.txt
        working-directory: ./data-mining
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./data-mining/raw-data
          file: ./data-mining/raw-data/Dockerfile
          platforms: linux/amd64
          push: true
          tags:  ghcr.io/ding-ma/riot-raw-data-scraper:latest
