name: Docker Image - Riot Scraper Raw Data

on: [push]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_CONTAINER_REGISTRY }}
      - name: Install pip
        run: |
          pip install --upgrade pip
          sudo -H pip install -U pipenv
      - name: Install pipenv
        env:
          PYTHON_BIN_PATH: "$(python3 -m site --user-base)/bin"
          PATH: "$PATH:$PYTHON_BIN_PATH"
        run: |  
          pipenv install
          pipenv lock -r > raw-data/requirements.txt
        working-directory: ./data-mining
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./data-mining/raw-data
          file: ./data-mining/raw-data/Dockerfile
          platforms: linux/amd64
          push: true
          tags:  ghcr.io/ding-ma/riot-raw-data-scraper:latest
